ckpt:
  OPTIMIZATION_MODE: min
  TOP_K_CKPT_TO_BE_SAVED: 2
data_preprocessing:
  BATCH_SIZE_FOR_DATA_LOADER: 1000
  COL_WISE_PERCENT_NULL_VALUES_THRESH: 0.2
  DATA_SPLIT_RANDOM_STATE: 43
  KNN_IMPUTER_NEIGHBORS: 3
  ROW_WISE_PERCENT_NULL_VALUES_THRESHOLD: 0.4
  TARGET_COLUMN_NAME: device_category
  TEST_SIZE: 0.2
input_features_schema:
  B_is_system_port: int64
  B_is_user_port: int64
  ack: int64
  ack_A: int64
  ack_B: int64
  bytes: int64
  bytes_A: int64
  bytes_A_B_ratio: float64
  bytes_B: int64
  ds_field_B: int64
  duration: float64
  http_bytes_avg: float64
  http_bytes_firstQ: float64
  http_bytes_max: int64
  http_bytes_median: float64
  http_bytes_min: int64
  http_bytes_stdev: float64
  http_bytes_sum: int64
  http_bytes_thirdQ: float64
  http_bytes_var: float64
  http_cookie_count: int64
  http_count_transactions: int64
  http_dom_host_alexaRank: int64
  http_dom_resp_code: int64
  http_inter_arrivel_avg: float64
  http_inter_arrivel_firstQ: float64
  http_inter_arrivel_max: float64
  http_inter_arrivel_median: float64
  http_inter_arrivel_min: float64
  http_inter_arrivel_stdev: float64
  http_inter_arrivel_sum: float64
  http_inter_arrivel_thirdQ: float64
  http_inter_arrivel_var: float64
  http_req_bytes_avg: int64
  http_req_bytes_firstQ: int64
  http_req_bytes_max: int64
  http_req_bytes_median: int64
  http_req_bytes_min: int64
  http_req_bytes_sum: int64
  http_req_bytes_thirdQ: int64
  http_resp_bytes_avg: float64
  http_resp_bytes_firstQ: float64
  http_resp_bytes_max: int64
  http_resp_bytes_median: float64
  http_resp_bytes_min: int64
  http_resp_bytes_stdev: float64
  http_resp_bytes_sum: int64
  http_resp_bytes_thirdQ: float64
  http_resp_bytes_var: float64
  http_time_avg: float64
  http_time_firstQ: float64
  http_time_max: float64
  http_time_median: float64
  http_time_min: float64
  http_time_stdev: float64
  http_time_sum: float64
  http_time_thirdQ: float64
  http_time_var: float64
  packet_inter_arrivel_A_avg: float64
  packet_inter_arrivel_A_entropy: float64
  packet_inter_arrivel_A_firstQ: float64
  packet_inter_arrivel_A_max: float64
  packet_inter_arrivel_A_median: float64
  packet_inter_arrivel_A_stdev: float64
  packet_inter_arrivel_A_sum: float64
  packet_inter_arrivel_A_thirdQ: float64
  packet_inter_arrivel_A_var: float64
  packet_inter_arrivel_B_avg: float64
  packet_inter_arrivel_B_entropy: float64
  packet_inter_arrivel_B_firstQ: float64
  packet_inter_arrivel_B_max: float64
  packet_inter_arrivel_B_median: float64
  packet_inter_arrivel_B_stdev: float64
  packet_inter_arrivel_B_sum: float64
  packet_inter_arrivel_B_thirdQ: float64
  packet_inter_arrivel_B_var: float64
  packet_inter_arrivel_avg: float64
  packet_inter_arrivel_entropy: float64
  packet_inter_arrivel_max: float64
  packet_inter_arrivel_stdev: float64
  packet_inter_arrivel_sum: float64
  packet_inter_arrivel_thirdQ: float64
  packet_inter_arrivel_var: float64
  packet_size_A_avg: float64
  packet_size_A_entropy: float64
  packet_size_A_firstQ: float64
  packet_size_A_max: int64
  packet_size_A_median: float64
  packet_size_A_min: int64
  packet_size_A_stdev: float64
  packet_size_A_sum: int64
  packet_size_A_thirdQ: float64
  packet_size_A_var: float64
  packet_size_B_avg: float64
  packet_size_B_entropy: float64
  packet_size_B_firstQ: float64
  packet_size_B_max: int64
  packet_size_B_median: float64
  packet_size_B_stdev: float64
  packet_size_B_sum: int64
  packet_size_B_thirdQ: float64
  packet_size_B_var: float64
  packet_size_avg: float64
  packet_size_entropy: float64
  packet_size_firstQ: float64
  packet_size_max: int64
  packet_size_median: float64
  packet_size_stdev: float64
  packet_size_sum: int64
  packet_size_thirdQ: float64
  packet_size_var: float64
  packets: int64
  packets_A: int64
  packets_B: int64
  push: int64
  push_A: int64
  push_B: int64
  reset: int64
  reset_A: int64
  ssl_count_certificates: int64
  ssl_count_client_cipher_algs: int64
  ssl_count_client_ciphersuites: int64
  ssl_count_client_elliptic_curves: int64
  ssl_count_client_key_exchange_algs: int64
  ssl_count_client_mac_algs: int64
  ssl_dom_server_ciphersuite: int64
  ssl_dom_server_name_alexaRank: int64
  ssl_dom_version: int64
  ssl_handshake_duration_avg: float64
  ssl_handshake_duration_firstQ: float64
  ssl_handshake_duration_max: float64
  ssl_handshake_duration_median: float64
  ssl_handshake_duration_min: float64
  ssl_handshake_duration_sum: float64
  ssl_handshake_duration_thirdQ: float64
  ssl_req_bytes_avg: float64
  ssl_req_bytes_entropy: float64
  ssl_req_bytes_firstQ: float64
  ssl_req_bytes_max: int64
  ssl_req_bytes_median: float64
  ssl_req_bytes_min: int64
  ssl_req_bytes_stdev: float64
  ssl_req_bytes_sum: int64
  ssl_req_bytes_thirdQ: float64
  ssl_req_bytes_var: float64
  ssl_resp_bytes_avg: float64
  ssl_resp_bytes_firstQ: float64
  ssl_resp_bytes_max: int64
  ssl_resp_bytes_median: float64
  ssl_resp_bytes_min: int64
  ssl_resp_bytes_stdev: float64
  ssl_resp_bytes_sum: int64
  ssl_resp_bytes_thirdQ: float64
  ssl_resp_bytes_var: float64
  suffix_is_else: int64
  suffix_is_empty_char_value: int64
  tcp_analysis_duplicate_ack: int64
  tcp_analysis_keep_alive: int64
  tcp_analysis_lost_segment: int64
  tcp_analysis_out_of_order: int64
  tcp_analysis_retransmission: int64
  tcp_analysis_reused_ports: int64
  ttl_A_avg: int64
  ttl_A_firstQ: int64
  ttl_A_max: int64
  ttl_A_median: int64
  ttl_A_min: int64
  ttl_A_sum: int64
  ttl_A_thirdQ: int64
  ttl_B_avg: float64
  ttl_B_entropy: float64
  ttl_B_firstQ: float64
  ttl_B_max: int64
  ttl_B_median: float64
  ttl_B_min: int64
  ttl_B_stdev: float64
  ttl_B_sum: int64
  ttl_B_thirdQ: float64
  ttl_B_var: float64
  ttl_avg: float64
  ttl_entropy: float64
  ttl_firstQ: float64
  ttl_max: int64
  ttl_median: float64
  ttl_min: int64
  ttl_stdev: float64
  ttl_sum: int64
  ttl_thirdQ: float64
  ttl_var: float64
labels_mapping:
  0: TV
  1: baby_monitor
  2: lights
  3: motion_sensor
  4: security_camera
  5: smoke_detector
  6: socket
  7: thermostat
  8: watch
  9: water_sensor
ml:
  ACCELERATOR: gpu
  DEVICES:
  - 0
  EARLY_STOPPING_PATIENCE: 5
  LEARNING_RATE: 0.001
  MAX_NUMBER_OF_EPOCHS: 10
  METRICS_TO_TRACK: val_loss
  MIN_NUMBER_OF_EPOCHS: 5
  MODEL_BLESSING_THRESHOLD: 0.0
  MODEL_BLESSING_THRESHOLD_COMPARISION: true
  PRECISION: 16
model_monitoring:
  CHECK_DATA_DRIFT: true
  DATA_DRIFT_P_VALUE_THRESHOLD: 0.05
