apiVersion : apps/v1
kind: Deployment
metadata:
  name: iotdeviceidentification 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: iotdeviceidentification
  template:
    metadata:
      labels:
        app: iotdeviceidentification 
    spec:
      containers:
        - name: iotdeviceidentification 
          image: devopspublic.azurecr.io/iotdeviceidentification
          ports:
          - containerPort: 8080
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: iot-secret
                key: mysql-db-host
          - name: DB_NAME
            valueFrom: 
              secretKeyRef:
                name: iot-secret
                key: mysql-db-name
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: iot-secret
                key: mysql-db-user
          - name: DB_PASS
            valueFrom: 
              secretKeyRef:
                name: iot-secret
                key: mysql-db-pswd
          - name: JWT_AUTH_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: iot-secret
                key: jwt-auth-secret-key
          - name: JWT_AUTH_ALGORITHM
            valueFrom: 
              secretKeyRef:
                name: iot-secret
                key: jwt-auth-algorithm
      # imagePullSecrets:
      # - name: regcred